# Notes: 
# Use Python-style True or False for boolean values
# Include trailing spaces for all "extra" parameters
genome: hg38
ensembl_genome_build: "110"
apply_spike_in: True
spike_in_genome: MG1655
spike_in_ensembl_genome_build: "57"
cutadapt:
  a: AGATCGGAAGAGCACACGTCTGAACTCCAGTCA;min_overlap=6
  A: AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT;min_overlap=6
  extra: "-q 20 " # Quality score cutoff
  min_length: 30
remove_MT_seqs: True # Create bowtie2 index without MT sequences
bowtie2:
  min_length: 10 # The minimum fragment length for valid paired-end alignments
  max_length: 700 # The maximum fragment length for valid paired-end alignments
  MAPQ_cutoff: 5 # Skip alignments with MAPQ smaller than this value
  extra: "" # Extra parameters for bowtie2
  samtools_extra: "" # Extra parameters for samtools
deduplication: False
bigwig:
  normalisation: RPKM # Will be ignored if spike-in is applied
  binsize: 10
  extra: "--skipZeros "
resources: # computing resources
  trim:
    cpu: 8
    time: 60
  fastqc:
    cpu: 4
    time: 60
  index:
    cpu: 36
    time: 60
  mapping:
    cpu: 10
    time: 120
  samtools:
    cpu: 4
    time: 30
  deeptools:
    cpu: 6
    time: 60
  deseq2:
    cpu: 6
    time: 60 
  plotting:
    cpu: 2
    time: 20
