on:
  push:
    branches:
      - main

name: release-please

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:

      - uses: GoogleCloudPlatform/release-please-action@v3
        id: release
        with:
          release-type: simple # just keep a changelog, no version anywhere outside of git tags
          token: ${{ secrets.GITHUB_TOKEN }}
